In [19]:
import numpy as np

def no_numpy_mult(first, second):
    result = []
    size = len(first)
    for i in range(size):
        t = []
        for j in range(size):
            r = 0
            for k in range(size):
                r = r+first[i][k]*second[k][j]
            t.append(r)
        result.append(t)
    return result
            
def numpy_mult(first, second):
    """
    param first: np.array[size, size]
    param second: np.array[size, size]
    """

    #YOUR CODE: please use numpy

    result = first.dot(second)
    return result

In [20]:
a = [[1, 2], [3, 4]]
b = [[-4, 6], [19, -7]]
print(no_numpy_mult(a, b))
print(numpy_mult(np.array(a), np.array(b)))

[[34, -8], [64, -10]]
[[ 34  -8]
 [ 64 -10]]


In [32]:
import numpy as np
a = np.array([[[1, 2, 3], [7, 8, 9]],
              [[4, 5, 6], [3, 2, 1]]])
b = np.array([[[3, 2, 1], [1, 7, 2]],
              [[7, 1, 5], [4, 1, 8]]])
c = np.concatenate((a, b), axis=2)
print(c)

[[[1 2 3 3 2 1]
  [7 8 9 1 7 2]]

 [[4 5 6 7 1 5]
  [3 2 1 4 1 8]]]


In [29]:
a = np.array([1, 2, 3])
b = np.array([5, 6, 7])
c = np.concatenate((a, b), axis=0)
print(c)

[1 2 3 5 6 7]


In [125]:
import numpy as np

def transform(X, a=1):
    """
    param X: np.array[batch_size, n]
    """
    y = np.copy(X)
    result = []
    n = len(y)
    if ((X.size / X.shape[0]) == 1): 
        n = 1
    
    if (n > 1):
        for i in range(n):
            for j in range(len(y[i])):
                if (j%2): 
                    y[i][j] = y[i][j] **3
                else: 
                    y[i][j] = a 
            result.append(np.concatenate((X[i], y[i][::-1]), axis=0))
    else: 
        for j in range(len(y)):
                if (j%2): 
                    y[j] = y[j] **3
                else: 
                    y[j] = a 
        result = np.copy(X)
        result2= []
        result2 = np.array(result2)
        
        for i in range(len(y)):
            np.concatenate((result2, y[len(y)-1-i]), axis=1)
        print(result2)
           
    return result

In [126]:
x = np.array([100,200,300,400,500])
print(transform(x, 1))



x = np.array([[100,200,300,400,500], [1, 2, 4, 5, 6]])
print(transform(x, 1))

AxisError: axis 1 is out of bounds for array of dimension 1

In [88]:
from tqdm import tqdm
i = 0
for line in tqdm(range(10000000000), ascii=True, dynamic_ncols=True, total=i, unit=" lines"):
        i += 1

10000000000 lines [1:35:45, 1740562.05 lines/s]
